In [1]:
#Все библиотеки тут:
#для парсинга
import requests
from bs4 import BeautifulSoup
import pandas as pd
import time
from tqdm import tqdm
import random
import csv

#для препроцессинга
import re
import nltk
from nltk.corpus import stopwords
from nltk.stem import SnowballStemmer, WordNetLemmatizer
nltk.download('punkt')
nltk.download('stopwords')
nltk.download('wordnet')
nltk.download('punkt_tab')

#для добавления запросов
import json
import requests
from typing import List, Dict
import uuid
import google.generativeai as genai
from typing import List, Dict
from transformers import AutoModelForCausalLM, AutoTokenizer
from transformers import BitsAndBytesConfig
import torch
import random

#для обучения

from sklearn.metrics.pairwise import cosine_similarity
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import confusion_matrix, classification_report, ConfusionMatrixDisplay
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import accuracy_score, classification_report
from sklearn.pipeline import Pipeline
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.utils.class_weight import compute_sample_weight
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.manifold import TSNE
from sklearn.cluster import KMeans
from sklearn.preprocessing import StandardScaler
from sklearn.cluster import DBSCAN
from sklearn.decomposition import TruncatedSVD
from sklearn.metrics import silhouette_score
from sklearn.metrics import adjusted_rand_score
from sklearn.decomposition import PCA
from sklearn.utils import resample
from scipy.stats import mode
from scipy.sparse import issparse 
from sklearn.naive_bayes import (MultinomialNB, ComplementNB)
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import f1_score
from sentence_transformers import SentenceTransformer
import torch

#для визуализации

[nltk_data] Error loading punkt: <urlopen error [SSL:
[nltk_data]     CERTIFICATE_VERIFY_FAILED] certificate verify failed:
[nltk_data]     unable to get local issuer certificate (_ssl.c:1032)>
[nltk_data] Error loading stopwords: <urlopen error [SSL:
[nltk_data]     CERTIFICATE_VERIFY_FAILED] certificate verify failed:
[nltk_data]     unable to get local issuer certificate (_ssl.c:1032)>
[nltk_data] Error loading wordnet: <urlopen error [SSL:
[nltk_data]     CERTIFICATE_VERIFY_FAILED] certificate verify failed:
[nltk_data]     unable to get local issuer certificate (_ssl.c:1032)>
[nltk_data] Error loading punkt_tab: <urlopen error [SSL:
[nltk_data]     CERTIFICATE_VERIFY_FAILED] certificate verify failed:
[nltk_data]     unable to get local issuer certificate (_ssl.c:1032)>
/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
/var/folders/ny/7y8fs2114hjdg150zcnmhwfh0000gn/T/ipykernel_1346/969190695.py:26: FutureWarning:

All support for the `google.generativeai` package has ended. It will no longer be receiving
updates or bug fixes. Please switch to the `google.genai` package as soon as possible.
See README for more details:

https://github.com/google-gemini/deprecated-generative-ai-python/blob/main/README.md

  import google.generativeai as genai

In [ ]:
#начинаем с парсинга данных
#задача: собрать табличку книга-аннотация-сслыка на книгу с сайта издательства Бомбора

timeout = (5, 20)
delay_min = 0.5
delay_max = 1.5

books_data = []

for i in tqdm(range(len(book_links))):
    try:
        time.sleep(random.uniform(delay_min, delay_max))
        page = requests.get(book_links[i], timeout=timeout)
        
        if page.status_code != 200:
            books_data.append(['Ошибка загрузки', 'Ошибка загрузки', book_links[i]])
            continue
        
        soup = BeautifulSoup(page.text, 'html.parser')
        
        # Поиск заголовка (пробуем разные варианты)
        title_selectors = [
            'h1.book-overview_title.h2',
            'h1.book-overview__title',
            'h1[class*="title"]',
            'h1'
        ]
        
        title = None
        for selector in title_selectors:
            elem = soup.select_one(selector)
            if elem:
                title = elem.text.strip()
                break
        
        # Поиск описания
        annotation_selectors = [
            '.book-overview_text',
            '.book-overview__text',
            '[class*="annotation"]',
            '[class*="description"]',
            '.book-description'
        ]
        
        annotation = None
        for selector in annotation_selectors:
            elem = soup.select_one(selector)
            if elem:
                annotation = elem.text.strip()
                break
        
        # Если описание не найдено, ищем длинный текст
        if not annotation:
            for p in soup.find_all(['p', 'div']):
                text = p.text.strip()
                if len(text) > 100 and not p.find_parent(['header', 'footer', 'nav']):
                    annotation = text
                    break
        
        books_data.append([
            title if title else 'Заголовок не найден',
            annotation if annotation else 'Описание не найдено',
            book_links[i]
        ])
        
        # Логирование каждых 100 книг (#подсказал дипсик, чтобы отслеживать прогресс 
        # *большой объем и парсинг слетал в ошибку много раз до этого)
        if i % 100 == 0 and i > 0:
            print(f"Обработано {i} книг, успешно: {sum(1 for b in books_data if b[0] != 'Ошибка загрузки')}")
        
    except Exception as e:
        print(f"Ошибка {book_links[i]}: {e}")
        books_data.append(['Ошибка', f'Ошибка: {str(e)}', book_links[i]])
        continue

  1%|          | 101/17687 [04:18<9:27:08,  1.93s/it]

Обработано 100 книг, успешно: 101

  1%|          | 201/17687 [07:54<8:24:32,  1.73s/it]

Обработано 200 книг, успешно: 201

  2%|▏         | 301/17687 [11:15<10:17:47,  2.13s/it]

Обработано 300 книг, успешно: 301

  2%|▏         | 401/17687 [14:48<9:15:56,  1.93s/it]

Обработано 400 книг, успешно: 401

  3%|▎         | 501/17687 [18:20<9:56:30,  2.08s/it]

Обработано 500 книг, успешно: 501

  3%|▎         | 601/17687 [21:30<7:58:10,  1.68s/it]

Обработано 600 книг, успешно: 601

  4%|▍         | 701/17687 [24:57<10:59:23,  2.33s/it]

Обработано 700 книг, успешно: 701

  5%|▍         | 801/17687 [28:20<8:53:21,  1.90s/it]

Обработано 800 книг, успешно: 801

  5%|▌         | 901/17687 [31:39<7:13:33,  1.55s/it]

Обработано 900 книг, успешно: 901

  6%|▌         | 1001/17687 [35:13<9:14:38,  1.99s/it]

Обработано 1000 книг, успешно: 1001

  6%|▌         | 1101/17687 [38:25<8:41:42,  1.89s/it]

Обработано 1100 книг, успешно: 1101

  7%|▋         | 1201/17687 [41:42<9:48:07,  2.14s/it]

Обработано 1200 книг, успешно: 1201

  7%|▋         | 1301/17687 [45:09<8:21:38,  1.84s/it]

Обработано 1300 книг, успешно: 1301

  8%|▊         | 1401/17687 [48:27<8:14:53,  1.82s/it]

Обработано 1400 книг, успешно: 1401

  8%|▊         | 1501/17687 [51:55<9:01:30,  2.01s/it]

Обработано 1500 книг, успешно: 1501

  9%|▉         | 1601/17687 [55:20<9:11:02,  2.06s/it]

Обработано 1600 книг, успешно: 1601

 10%|▉         | 1701/17687 [58:24<7:01:14,  1.58s/it]

Обработано 1700 книг, успешно: 1701

 10%|█         | 1801/17687 [1:01:45<7:50:20,  1.78s/it]

Обработано 1800 книг, успешно: 1801

 10%|█         | 1837/17687 [1:03:04<21:08:38,  4.80s/it]

Ошибка https://www.litres.ru/book/elis-makabe/vyshivka-elis-makabe-shepot-vetra-v-sosnovoy-hvoe-prirodnye-su-72932935/?lfrom=452226304: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

 11%|█         | 1901/17687 [1:05:00<8:14:29,  1.88s/it]

Обработано 1900 книг, успешно: 1901

 11%|█▏        | 2001/17687 [1:08:16<7:58:03,  1.83s/it]

Обработано 2000 книг, успешно: 2001

 12%|█▏        | 2101/17687 [1:11:29<8:06:16,  1.87s/it]

Обработано 2100 книг, успешно: 2101

 12%|█▏        | 2201/17687 [1:14:50<8:24:11,  1.95s/it]

Обработано 2200 книг, успешно: 2201

 13%|█▎        | 2301/17687 [1:18:33<17:39:24,  4.13s/it]

Обработано 2300 книг, успешно: 2301

 14%|█▎        | 2401/17687 [1:21:56<10:08:33,  2.39s/it]

Обработано 2400 книг, успешно: 2401

 14%|█▍        | 2501/17687 [1:25:09<8:15:11,  1.96s/it]

Обработано 2500 книг, успешно: 2501

 15%|█▍        | 2601/17687 [1:28:20<6:52:08,  1.64s/it]

Обработано 2600 книг, успешно: 2601

 15%|█▌        | 2701/17687 [1:31:48<9:31:10,  2.29s/it]

Обработано 2700 книг, успешно: 2701

 16%|█▌        | 2801/17687 [1:35:30<7:25:19,  1.79s/it]

Обработано 2800 книг, успешно: 2801

 16%|█▋        | 2901/17687 [1:39:13<14:16:53,  3.48s/it]

Обработано 2900 книг, успешно: 2901

 17%|█▋        | 3001/17687 [1:42:58<9:43:14,  2.38s/it]

Обработано 3000 книг, успешно: 3001

 18%|█▊        | 3101/17687 [1:46:50<7:13:38,  1.78s/it]

Обработано 3100 книг, успешно: 3101

 18%|█▊        | 3201/17687 [1:50:20<7:38:20,  1.90s/it]

Обработано 3200 книг, успешно: 3201

 19%|█▊        | 3301/17687 [1:53:35<9:01:07,  2.26s/it]

Обработано 3300 книг, успешно: 3301

 19%|█▉        | 3394/17687 [1:56:57<18:15:52,  4.60s/it]

Ошибка https://www.litres.ru/book/alena-shah/zhenschina-alfa-kak-upravlyat-svoey-zhiznu-bez-oglyadki-na-chuz-72215932/?lfrom=452226304: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

 19%|█▉        | 3401/17687 [1:57:12<11:08:02,  2.81s/it]

Обработано 3400 книг, успешно: 3399

 20%|█▉        | 3501/17687 [2:00:49<7:33:07,  1.92s/it]

Обработано 3500 книг, успешно: 3499

 20%|██        | 3601/17687 [2:04:09<7:15:48,  1.86s/it]

Обработано 3600 книг, успешно: 3599

 21%|██        | 3701/17687 [2:07:42<8:40:31,  2.23s/it]

Обработано 3700 книг, успешно: 3699

 21%|██▏       | 3801/17687 [2:10:37<7:12:13,  1.87s/it]

Обработано 3800 книг, успешно: 3799

 22%|██▏       | 3884/17687 [2:13:35<14:10:05,  3.70s/it]

Ошибка https://www.litres.ru/book/valeriy-komskov/vvedenie-v-professiu-biznes-analitika-otpravnaya-tochka-dl-71793763/?lfrom=452226304: HTTPSConnectionPool(host='www.litres.ru', port=443): Read timed out. (read timeout=5)

 22%|██▏       | 3901/17687 [2:14:10<8:26:19,  2.20s/it]

Обработано 3900 книг, успешно: 3899

 23%|██▎       | 4001/17687 [2:17:10<5:52:30,  1.55s/it]

Обработано 4000 книг, успешно: 3999

 23%|██▎       | 4101/17687 [2:20:27<6:24:46,  1.70s/it]

Обработано 4100 книг, успешно: 4099

 24%|██▍       | 4201/17687 [2:23:32<5:52:59,  1.57s/it]

Обработано 4200 книг, успешно: 4199

 24%|██▍       | 4301/17687 [2:26:47<7:50:40,  2.11s/it]

Обработано 4300 книг, успешно: 4299

 25%|██▍       | 4401/17687 [2:30:08<5:26:00,  1.47s/it]

Обработано 4400 книг, успешно: 4399

 25%|██▌       | 4501/17687 [2:33:38<18:13:47,  4.98s/it]

Обработано 4500 книг, успешно: 4499

 25%|██▌       | 4503/17687 [2:33:52<23:08:19,  6.32s/it]

Ошибка https://www.litres.ru/book/alla-subbota/master-i-margarita-kulinarnaya-vselennaya-kultovogo-romana-71583439/?lfrom=452226304: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

 26%|██▌       | 4601/17687 [2:37:21<7:16:03,  2.00s/it]

Обработано 4600 книг, успешно: 4599

 27%|██▋       | 4701/17687 [2:40:57<6:51:58,  1.90s/it]

Обработано 4700 книг, успешно: 4699

 27%|██▋       | 4801/17687 [2:44:40<6:51:00,  1.91s/it]

Обработано 4800 книг, успешно: 4799

 28%|██▊       | 4901/17687 [2:48:34<7:50:19,  2.21s/it]

Обработано 4900 книг, успешно: 4899

 28%|██▊       | 5001/17687 [2:52:25<7:52:20,  2.23s/it]

Обработано 5000 книг, успешно: 4999

 29%|██▉       | 5101/17687 [2:56:15<8:06:27,  2.32s/it]

Обработано 5100 книг, успешно: 5099

 29%|██▉       | 5201/17687 [2:59:48<6:40:27,  1.92s/it]

Обработано 5200 книг, успешно: 5199

 30%|██▉       | 5301/17687 [3:02:54<6:12:32,  1.80s/it]

Обработано 5300 книг, успешно: 5299

 31%|███       | 5401/17687 [3:06:24<8:04:00,  2.36s/it]

Обработано 5400 книг, успешно: 5399

 31%|███       | 5501/17687 [3:09:51<6:37:48,  1.96s/it]

Обработано 5500 книг, успешно: 5499

 32%|███▏      | 5601/17687 [3:13:21<8:35:18,  2.56s/it]

Обработано 5600 книг, успешно: 5599

 32%|███▏      | 5701/17687 [3:16:42<7:17:17,  2.19s/it]

Обработано 5700 книг, успешно: 5699

 33%|███▎      | 5801/17687 [3:19:57<6:38:32,  2.01s/it]

Обработано 5800 книг, успешно: 5799

 33%|███▎      | 5901/17687 [3:23:23<5:55:23,  1.81s/it]

Обработано 5900 книг, успешно: 5899

 34%|███▍      | 6001/17687 [3:26:55<8:12:30,  2.53s/it]

Обработано 6000 книг, успешно: 5999

 34%|███▍      | 6101/17687 [3:30:12<6:32:30,  2.03s/it]

Обработано 6100 книг, успешно: 6099

 35%|███▌      | 6201/17687 [3:33:13<4:42:52,  1.48s/it]

Обработано 6200 книг, успешно: 6199

 36%|███▌      | 6301/17687 [3:36:43<5:15:46,  1.66s/it]

Обработано 6300 книг, успешно: 6299

 36%|███▌      | 6401/17687 [3:39:54<6:02:28,  1.93s/it]

Обработано 6400 книг, успешно: 6399

 37%|███▋      | 6482/17687 [3:42:47<15:37:35,  5.02s/it]

Ошибка https://www.litres.ru/book/natalya-malceva-3301/ne-podarili-a-navyazala-kak-postroit-biznes-i-luchshu-70567255/?lfrom=452226304: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

 37%|███▋      | 6501/17687 [3:43:28<6:05:04,  1.96s/it]

Обработано 6500 книг, успешно: 6499

 37%|███▋      | 6601/17687 [3:47:06<8:44:22,  2.84s/it]

Обработано 6600 книг, успешно: 6599

 38%|███▊      | 6701/17687 [3:50:26<6:48:58,  2.23s/it]

Обработано 6700 книг, успешно: 6699

 38%|███▊      | 6801/17687 [3:54:08<6:21:26,  2.10s/it]

Обработано 6800 книг, успешно: 6799

 39%|███▉      | 6901/17687 [3:57:26<7:45:36,  2.59s/it]

Обработано 6900 книг, успешно: 6899

 40%|███▉      | 7001/17687 [4:00:48<7:50:12,  2.64s/it]

Обработано 7000 книг, успешно: 6999

 40%|███▉      | 7048/17687 [4:02:42<23:59:05,  8.12s/it]

Ошибка https://bombora.ru/book/90325/: HTTPSConnectionPool(host='bombora.ru', port=443): Read timed out. (read timeout=20)

 40%|████      | 7077/17687 [4:03:57<23:10:15,  7.86s/it]

Ошибка https://bombora.ru/book/89775/: HTTPSConnectionPool(host='bombora.ru', port=443): Read timed out. (read timeout=20)

 40%|████      | 7101/17687 [4:04:44<4:54:46,  1.67s/it]

Обработано 7100 книг, успешно: 7099

 41%|████      | 7201/17687 [4:07:57<4:47:32,  1.65s/it]

Обработано 7200 книг, успешно: 7199

 41%|████▏     | 7301/17687 [4:11:12<6:26:10,  2.23s/it]

Обработано 7300 книг, успешно: 7299

 42%|████▏     | 7401/17687 [4:14:26<4:29:38,  1.57s/it]

Обработано 7400 книг, успешно: 7399

 42%|████▏     | 7501/17687 [4:17:43<4:55:37,  1.74s/it]

Обработано 7500 книг, успешно: 7499

 43%|████▎     | 7601/17687 [4:20:54<5:11:21,  1.85s/it]

Обработано 7600 книг, успешно: 7599

 44%|████▎     | 7701/17687 [4:24:09<5:16:58,  1.90s/it]

Обработано 7700 книг, успешно: 7699

 44%|████▍     | 7801/17687 [4:27:22<6:04:40,  2.21s/it]

Обработано 7800 книг, успешно: 7799

 45%|████▍     | 7901/17687 [4:30:34<4:47:44,  1.76s/it]

Обработано 7900 книг, успешно: 7899

 45%|████▌     | 8001/17687 [4:34:10<4:46:55,  1.78s/it]

Обработано 8000 книг, успешно: 7999

 46%|████▌     | 8101/17687 [4:38:44<7:31:32,  2.83s/it]

Обработано 8100 книг, успешно: 8099

 46%|████▌     | 8125/17687 [4:39:50<19:59:51,  7.53s/it]

Ошибка https://bombora.ru/book/88274/: HTTPSConnectionPool(host='bombora.ru', port=443): Read timed out. (read timeout=20)

 46%|████▋     | 8201/17687 [4:42:18<5:04:43,  1.93s/it]

Обработано 8200 книг, успешно: 8199

 47%|████▋     | 8301/17687 [4:45:34<5:24:19,  2.07s/it]

Обработано 8300 книг, успешно: 8299

 47%|████▋     | 8401/17687 [4:48:46<4:41:58,  1.82s/it]

Обработано 8400 книг, успешно: 8399

 48%|████▊     | 8501/17687 [4:52:11<4:59:18,  1.96s/it]

Обработано 8500 книг, успешно: 8499

 49%|████▊     | 8601/17687 [4:55:36<4:38:37,  1.84s/it]

Обработано 8600 книг, успешно: 8599

 49%|████▉     | 8701/17687 [4:58:42<4:49:58,  1.94s/it]

Обработано 8700 книг, успешно: 8699

 50%|████▉     | 8801/17687 [5:02:05<5:17:40,  2.15s/it]

Обработано 8800 книг, успешно: 8799

 50%|█████     | 8901/17687 [5:05:43<5:02:37,  2.07s/it]

Обработано 8900 книг, успешно: 8899

 51%|█████     | 9001/17687 [5:09:14<7:25:53,  3.08s/it]

Обработано 9000 книг, успешно: 8999

 51%|█████▏    | 9101/17687 [5:12:30<3:46:42,  1.58s/it]

Обработано 9100 книг, успешно: 9099

 52%|█████▏    | 9201/17687 [5:16:12<4:10:40,  1.77s/it]

Обработано 9200 книг, успешно: 9199

 53%|█████▎    | 9301/17687 [5:19:25<4:06:10,  1.76s/it]

Обработано 9300 книг, успешно: 9299

 53%|█████▎    | 9401/17687 [5:22:40<3:57:31,  1.72s/it]

Обработано 9400 книг, успешно: 9399

 54%|█████▎    | 9501/17687 [5:26:02<4:55:52,  2.17s/it]

Обработано 9500 книг, успешно: 9499

 54%|█████▍    | 9601/17687 [5:29:34<4:30:03,  2.00s/it]

Обработано 9600 книг, успешно: 9599

 55%|█████▍    | 9701/17687 [5:32:37<4:32:48,  2.05s/it]

Обработано 9700 книг, успешно: 9699

 55%|█████▌    | 9801/17687 [5:35:44<4:32:43,  2.08s/it]

Обработано 9800 книг, успешно: 9799

 56%|█████▌    | 9901/17687 [5:39:22<3:53:35,  1.80s/it]

Обработано 9900 книг, успешно: 9899

 57%|█████▋    | 10001/17687 [5:42:45<5:03:26,  2.37s/it]

Обработано 10000 книг, успешно: 9999

 57%|█████▋    | 10101/17687 [5:46:12<3:44:20,  1.77s/it]

Обработано 10100 книг, успешно: 10099

 58%|█████▊    | 10201/17687 [5:49:40<4:14:40,  2.04s/it]

Обработано 10200 книг, успешно: 10199

 58%|█████▊    | 10301/17687 [5:52:56<4:25:15,  2.15s/it]

Обработано 10300 книг, успешно: 10299

 59%|█████▉    | 10401/17687 [5:56:29<3:47:38,  1.87s/it]

Обработано 10400 книг, успешно: 10399

 59%|█████▉    | 10501/17687 [5:59:49<3:51:01,  1.93s/it]

Обработано 10500 книг, успешно: 10499

 60%|█████▉    | 10533/17687 [6:00:55<8:57:23,  4.51s/it]

Ошибка https://www.litres.ru/book/serafim-sarovskiy/izbrannye-duhovnye-nastavleniya-utesheniya-i-prorochestv-67231435/?lfrom=452226304: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

 60%|█████▉    | 10601/17687 [6:03:35<4:10:37,  2.12s/it]

Обработано 10600 книг, успешно: 10599

 61%|██████    | 10701/17687 [6:06:58<4:01:54,  2.08s/it]

Обработано 10700 книг, успешно: 10699

 61%|██████    | 10801/17687 [6:10:25<3:32:43,  1.85s/it]

Обработано 10800 книг, успешно: 10799

 62%|██████▏   | 10901/17687 [6:13:49<4:45:45,  2.53s/it]

Обработано 10900 книг, успешно: 10898

 62%|██████▏   | 11001/17687 [6:17:11<3:55:24,  2.11s/it]

Обработано 11000 книг, успешно: 10998

 63%|██████▎   | 11101/17687 [6:20:55<3:09:44,  1.73s/it]

Обработано 11100 книг, успешно: 11098

 63%|██████▎   | 11171/17687 [6:23:31<8:33:14,  4.73s/it]

Ошибка https://www.litres.ru/book/mariya-kicha/dinastii-kak-ustroena-vlast-v-sovremennyh-arabskih-monarhiyah-66553414/?lfrom=452226304: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

 63%|██████▎   | 11201/17687 [6:24:31<4:04:28,  2.26s/it]

Обработано 11200 книг, успешно: 11198

 64%|██████▍   | 11301/17687 [6:28:06<3:14:51,  1.83s/it]

Обработано 11300 книг, успешно: 11298

 64%|██████▍   | 11401/17687 [6:31:36<3:29:24,  2.00s/it]

Обработано 11400 книг, успешно: 11398

 65%|██████▌   | 11501/17687 [6:35:08<4:10:32,  2.43s/it]

Обработано 11500 книг, успешно: 11498

 65%|██████▌   | 11575/17687 [6:38:11<8:19:48,  4.91s/it]

Ошибка https://www.litres.ru/book/piter-krauch/kakovo-byt-futbolistom-zabavnye-istorii-iz-razdevalok-i-ne-to-65910329/?lfrom=452226304: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

 66%|██████▌   | 11601/17687 [6:39:13<4:31:41,  2.68s/it]

Обработано 11600 книг, успешно: 11598

 66%|██████▌   | 11701/17687 [6:42:38<4:33:37,  2.74s/it]

Обработано 11700 книг, успешно: 11697

 67%|██████▋   | 11801/17687 [6:46:18<3:24:46,  2.09s/it]

Обработано 11800 книг, успешно: 11792

 67%|██████▋   | 11901/17687 [6:50:02<4:05:19,  2.54s/it]

Обработано 11900 книг, успешно: 11892

 68%|██████▊   | 12001/17687 [6:53:22<2:31:09,  1.60s/it]

Обработано 12000 книг, успешно: 11992

 68%|██████▊   | 12101/17687 [6:57:21<3:26:34,  2.22s/it]

Обработано 12100 книг, успешно: 12092

 69%|██████▉   | 12201/17687 [7:00:56<3:08:26,  2.06s/it]

Обработано 12200 книг, успешно: 12192

 70%|██████▉   | 12301/17687 [7:04:41<3:01:37,  2.02s/it]

Обработано 12300 книг, успешно: 12292

 70%|███████   | 12401/17687 [7:08:40<3:23:43,  2.31s/it]

Обработано 12400 книг, успешно: 12392

 71%|███████   | 12501/17687 [7:12:26<3:34:24,  2.48s/it]

Обработано 12500 книг, успешно: 12492

 71%|███████   | 12601/17687 [7:15:53<3:12:37,  2.27s/it]

Обработано 12600 книг, успешно: 12592

 72%|███████▏  | 12701/17687 [7:19:32<2:49:43,  2.04s/it]

Обработано 12700 книг, успешно: 12692

 72%|███████▏  | 12801/17687 [7:23:23<3:48:02,  2.80s/it]

Обработано 12800 книг, успешно: 12792

 73%|███████▎  | 12901/17687 [7:27:15<2:10:08,  1.63s/it]

Обработано 12900 книг, успешно: 12892

 74%|███████▎  | 13001/17687 [7:31:16<3:48:21,  2.92s/it]

Обработано 13000 книг, успешно: 12992

 74%|███████▍  | 13101/17687 [7:34:46<2:08:59,  1.69s/it]

Обработано 13100 книг, успешно: 13092

 75%|███████▍  | 13201/17687 [7:38:41<3:23:46,  2.73s/it]

Обработано 13200 книг, успешно: 13192

 75%|███████▌  | 13301/17687 [7:42:14<2:01:51,  1.67s/it]

Обработано 13300 книг, успешно: 13291

 76%|███████▌  | 13401/17687 [7:45:48<2:52:40,  2.42s/it]

Обработано 13400 книг, успешно: 13391

 76%|███████▋  | 13501/17687 [7:49:41<2:03:25,  1.77s/it]

Обработано 13500 книг, успешно: 13491

 77%|███████▋  | 13601/17687 [7:53:29<4:17:06,  3.78s/it]

Обработано 13600 книг, успешно: 13591

 77%|███████▋  | 13701/17687 [7:57:40<2:15:52,  2.05s/it]

Обработано 13700 книг, успешно: 13691

 78%|███████▊  | 13801/17687 [8:01:33<2:52:55,  2.67s/it]

Обработано 13800 книг, успешно: 13791

 79%|███████▊  | 13901/17687 [8:05:27<3:00:07,  2.85s/it]

Обработано 13900 книг, успешно: 13890

 79%|███████▉  | 14001/17687 [8:09:27<3:00:09,  2.93s/it]

Обработано 14000 книг, успешно: 13990

 80%|███████▉  | 14101/17687 [8:13:14<1:45:59,  1.77s/it]

Обработано 14100 книг, успешно: 14090

 80%|████████  | 14201/17687 [8:17:09<1:34:07,  1.62s/it]

Обработано 14200 книг, успешно: 14189

 81%|████████  | 14301/17687 [8:20:44<2:06:35,  2.24s/it]

Обработано 14300 книг, успешно: 14289

 81%|████████▏ | 14401/17687 [8:24:17<1:51:44,  2.04s/it]

Обработано 14400 книг, успешно: 14389

 82%|████████▏ | 14501/17687 [8:27:54<1:46:25,  2.00s/it]

Обработано 14500 книг, успешно: 14489

 83%|████████▎ | 14601/17687 [8:31:39<1:45:36,  2.05s/it]

Обработано 14600 книг, успешно: 14589

 83%|████████▎ | 14701/17687 [8:35:11<1:57:32,  2.36s/it]

Обработано 14700 книг, успешно: 14689

 83%|████████▎ | 14761/17687 [8:37:39<3:41:41,  4.55s/it]

Ошибка https://www.litres.ru/book/elena-volodina/dzen-v-bolshom-gorode-iskusstvo-plyt-po-techeniu-i-vsegda-o-38989074/?lfrom=452226304: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

 84%|████████▎ | 14801/17687 [8:39:03<1:24:42,  1.76s/it]

Обработано 14800 книг, успешно: 14789

 84%|████████▍ | 14901/17687 [8:42:36<1:32:37,  1.99s/it]

Обработано 14900 книг, успешно: 14889

 85%|████████▍ | 15001/17687 [8:46:10<1:43:45,  2.32s/it]

Обработано 15000 книг, успешно: 14989

 85%|████████▌ | 15101/17687 [8:50:04<1:23:52,  1.95s/it]

Обработано 15100 книг, успешно: 15088

 86%|████████▌ | 15201/17687 [8:53:56<1:08:03,  1.64s/it]

Обработано 15200 книг, успешно: 15188

 87%|████████▋ | 15301/17687 [8:57:56<2:08:32,  3.23s/it]

Обработано 15300 книг, успешно: 15288

 87%|████████▋ | 15335/17687 [8:59:17<3:06:57,  4.77s/it]

Ошибка https://www.litres.ru/book/david-d-burns/rugatsya-nelzya-miritsya-kak-prekraschat-i-predotvraschat-ko-38975139/?lfrom=452226304: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

 87%|████████▋ | 15391/17687 [9:01:18<3:01:14,  4.74s/it]

Ошибка https://www.litres.ru/book/dzho-navarro/tri-minuty-do-sudnogo-dnya-36619502/?lfrom=452226304: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

 87%|████████▋ | 15401/17687 [9:01:43<1:56:38,  3.06s/it]

Обработано 15400 книг, успешно: 15388

 88%|████████▊ | 15501/17687 [9:05:50<1:07:11,  1.84s/it]

Обработано 15500 книг, успешно: 15487

 88%|████████▊ | 15532/17687 [9:07:03<2:45:44,  4.61s/it]

Ошибка https://www.litres.ru/book/dzhudi-gruvs/filosofiya-v-komiksah-35487979/?lfrom=452226304: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

 88%|████████▊ | 15601/17687 [9:09:18<51:14,  1.47s/it]

Обработано 15600 книг, успешно: 15587

 88%|████████▊ | 15616/17687 [9:10:01<2:41:03,  4.67s/it]

Ошибка https://www.litres.ru/book/ramita-navai-15159407/gorod-lzhi-lubov-seks-smert-vsya-pravda-o-tegerane-33389087/?lfrom=452226304: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

 89%|████████▉ | 15701/17687 [9:13:21<1:34:04,  2.84s/it]

Обработано 15700 книг, успешно: 15686

 89%|████████▉ | 15801/17687 [9:16:52<59:20,  1.89s/it]

Обработано 15800 книг, успешно: 15786

 90%|████████▉ | 15901/17687 [9:20:08<45:18,  1.52s/it]

Обработано 15900 книг, успешно: 15886

 90%|█████████ | 16001/17687 [9:23:47<1:07:01,  2.39s/it]

Обработано 16000 книг, успешно: 15986

 91%|█████████ | 16101/17687 [9:27:09<40:45,  1.54s/it]

Обработано 16100 книг, успешно: 16086

 92%|█████████▏| 16201/17687 [9:30:26<50:33,  2.04s/it]

Обработано 16200 книг, успешно: 16186

 92%|█████████▏| 16301/17687 [9:33:36<41:49,  1.81s/it]

Обработано 16300 книг, успешно: 16286

 93%|█████████▎| 16401/17687 [9:36:49<41:38,  1.94s/it]

Обработано 16400 книг, успешно: 16386

 93%|█████████▎| 16501/17687 [9:40:02<32:33,  1.65s/it]

Обработано 16500 книг, успешно: 16486

 94%|█████████▍| 16601/17687 [9:43:22<31:17,  1.73s/it]

Обработано 16600 книг, успешно: 16586

 94%|█████████▍| 16701/17687 [9:46:27<21:18,  1.30s/it]

Обработано 16700 книг, успешно: 16686

 95%|█████████▍| 16801/17687 [9:49:10<20:14,  1.37s/it]

Обработано 16800 книг, успешно: 16786

 96%|█████████▌| 16901/17687 [9:52:29<32:01,  2.44s/it]

Обработано 16900 книг, успешно: 16886

 96%|█████████▌| 17001/17687 [9:55:22<18:04,  1.58s/it]

Обработано 17000 книг, успешно: 16986

 97%|█████████▋| 17101/17687 [9:58:13<19:40,  2.01s/it]

Обработано 17100 книг, успешно: 17086

 97%|█████████▋| 17201/17687 [10:01:09<13:39,  1.69s/it]

Обработано 17200 книг, успешно: 17186

 98%|█████████▊| 17301/17687 [10:04:00<09:39,  1.50s/it]

Обработано 17300 книг, успешно: 17286

 98%|█████████▊| 17401/17687 [10:06:55<06:59,  1.47s/it]

Обработано 17400 книг, успешно: 17386

 99%|█████████▉| 17501/17687 [10:09:50<05:24,  1.75s/it]

Обработано 17500 книг, успешно: 17486

100%|█████████▉| 17601/17687 [10:12:41<02:55,  2.04s/it]

Обработано 17600 книг, успешно: 17586

100%|█████████▉| 17651/17687 [10:14:25<02:56,  4.91s/it]

Ошибка https://www.litres.ru/book/dzhi-na-yang/podderzhivat-a-ne-vospityvat-dat-oporu-rebenku-chtoby-on-vyro-73171958/?lfrom=452226304: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

100%|██████████| 17687/17687 [10:15:38<00:00,  2.09s/it]

In [ ]:
#собираем все в табличку через пандас

books_df = pd.DataFrame(books_data)
books_df.columns = ['title', 'annotation', 'link']
books_df

In [ ]:
# Сохраняем результаты на устройство
books_df.to_csv('/Users/uliaocheretina/Desktop/Комп лингв/ML Practice/FINAL_PROJECT_ML/books_data.csv', index=False, encoding='utf-8-sig')

In [2]:
#читаем табличку уже с устройства и сохраняем в переменную
books_df = pd.read_csv('books_data.csv', encoding='utf-8')

In [3]:
books_df #проверка

,Название,Описание,Ссылка
0,"Любовь, которая убивает. Как распознать психол...","Эта книга для вас, если:\n - в отношениях вы ...",https://bombora.ru/book/185922/
1,"Python все в одном для чайников, 3-е издание","Все, что вам нужно знать, чтобы начать програм...",https://bombora.ru/book/179927/
2,Дневник Бекона из Роблокс. Новый мир! Книга 9,Присоединяйтесь к Билли Блоксу в захватывающем...,https://bombora.ru/book/186999/
3,Комплект из 3-х книг: Зигмунд Фрейд. Классика ...,Откройте для себя психоанализ с новым комплект...,https://bombora.ru/book/186910/
4,Под звездным дождем,Старшеклассница Сонька приезжает к бабушке в д...,https://bombora.ru/book/186909/
...,...,...,...
17682,Сопрано. Закулисная история легендарного сериала,"Подходит для смартфонов, планшетов на Android,...",https://www.litres.ru/book/maykl-imperioli/sop...
17683,Женщина. Тело. Как простые движения запускают ...,"Изменить жизнь к лучшему, начать «с понедельни...",https://bombora.ru/book/179009/
17684,Женщина. Тело. Как простые движения запускают ...,"Подходит для смартфонов, планшетов на Android,...",https://www.litres.ru/book/zarina-del-mar/zhen...
17685,Истории из Minecraft на английском. Читаем с у...,"Учить английский — это весело, особенно если т...",https://bombora.ru/book/178522/
17686,Истории из Minecraft на английском. Читаем с у...,Книга на английском,https://www.litres.ru/book/uliya-koryagina-336...

In [4]:
#создание и привязка лейбла названия книги к аннотации, 
# чтобы далее при финальном обучении название подтягивалось само к аннотации

books_df.columns = ['title', 'annotation', 'link'] #на англ удобнее обращаться к колонкам

# генерация уникального айдишника для каждой книги
books_df['book_id'] = [str(uuid.uuid4()) for _ in range(len(books_df))]

# обновляем таблицу 
books_df.to_csv('/Users/uliaocheretina/Desktop/Комп лингв/ML Practice/FINAL_PROJECT_ML/books_id.csv', index=False, encoding='utf-8')
print(f"Всего книг в базе: {len(books_df)}")

# посмотрела через дип сик, что для верности, лучше еще создать словарь 
# Ключ = ID книги, Значение = название книги и ссылка
book_info_id = dict(zip(books_df['book_id'], books_df['title']))
link_id = dict(zip(books_df['book_id'], books_df['link']))

Всего книг в базе: 17687

In [7]:
#также сохраним в переменную и проверка
books_df_id = pd.read_csv('books_id.csv', encoding='utf-8')
books_df_id

,title,annotation,link,book_id
0,"Любовь, которая убивает. Как распознать психол...","Эта книга для вас, если:\n - в отношениях вы ...",https://bombora.ru/book/185922/,cfe2a54e-d4ed-4d30-b625-c7b1dfcb18b4
1,"Python все в одном для чайников, 3-е издание","Все, что вам нужно знать, чтобы начать програм...",https://bombora.ru/book/179927/,1a7ebad7-1a84-461b-a7fd-ca02a17d9544
2,Дневник Бекона из Роблокс. Новый мир! Книга 9,Присоединяйтесь к Билли Блоксу в захватывающем...,https://bombora.ru/book/186999/,1a5212f7-b8c1-4b62-bff1-84935b6b64d9
3,Комплект из 3-х книг: Зигмунд Фрейд. Классика ...,Откройте для себя психоанализ с новым комплект...,https://bombora.ru/book/186910/,f5313349-d2d7-445e-acb4-c0f6a88a2d94
4,Под звездным дождем,Старшеклассница Сонька приезжает к бабушке в д...,https://bombora.ru/book/186909/,a78fba8c-f852-42c6-9104-69bf6958f6fa
...,...,...,...,...
17682,Сопрано. Закулисная история легендарного сериала,"Подходит для смартфонов, планшетов на Android,...",https://www.litres.ru/book/maykl-imperioli/sop...,635f73d2-652d-4628-a2e3-f0e09e8bcbf1
17683,Женщина. Тело. Как простые движения запускают ...,"Изменить жизнь к лучшему, начать «с понедельни...",https://bombora.ru/book/179009/,fed081ef-c5c5-4625-b17b-5c416e3dcbbd
17684,Женщина. Тело. Как простые движения запускают ...,"Подходит для смартфонов, планшетов на Android,...",https://www.litres.ru/book/zarina-del-mar/zhen...,f11ac5c3-6372-4ec9-96f9-a6d8f70a378b
17685,Истории из Minecraft на английском. Читаем с у...,"Учить английский — это весело, особенно если т...",https://bombora.ru/book/178522/,8d8adf0f-544f-46c0-b920-cf71744aaed5
17686,Истории из Minecraft на английском. Читаем с у...,Книга на английском,https://www.litres.ru/book/uliya-koryagina-336...,d76f4a89-2fe8-4923-8c0c-d47dead0ba29

In [8]:
# и еще одна привязка через словарь именно к аннотации
annotation_id = dict(zip(books_df_id['book_id'], books_df_id['annotation']))
book_info_id1 = dict(zip(books_df_id['book_id'], books_df_id['title']))
# пробуем получить аннотацию по айдишнику:
test_id = books_df_id['book_id'].iloc[90]  #тестовое

print(f"ID: {test_id}")
print(f"Название: {book_info_id1[test_id]}")
print(f"Аннотация: {annotation_id[test_id][:100]}...")

ID: 8dc2d217-f479-43ca-9b06-3f9d832ff5e3
Название: Ежедневник в стиле Хобоничи. Японский тренд. Сочные вишни.
Аннотация: Ежедневник в стиле хобоничи — для тех, кто любит японскую «тихую» продуктивность: когда планирование...

In [ ]:
#добавляем запросы пользователей к нашим данным, которые будут частью информации для Х при обучении: консультация у дип сика, первый опыт в интегрировании llm в код, а не запрос напрямую
#решила сделать микс из готового датасета с запросами с hugging face и синтетического, созданного с помощью llm
#upd: в финальную версию вошли только синтетические запросы, тк не хватило мощности и времени на полный сбор 

#генерим запросы через llm (c подсказкой дип сик)
def synthetic_queries_qwen( #беру квен, тк она бесплатная, неплохая для данной задачи + алибаба в целом показывают неплохие результаты на данный момент работ
    df: pd.DataFrame,
    queries_per_book: int = 4,
    max_retries: int = 3
) -> List[Dict]:
    """
    Генерация синтетических запросов через локальную модель Qwen
    """
    print("\n Генерация синтетических запросов через Qwen...")

    device = "cuda" if torch.cuda.is_available() else "cpu"

    # мы берем qwen (изначально хотелось попробовать поработать с claude или gemini, но клод платный, а джемини не удалось запустить даже с впн (чтобы получить код доступа))
    model_name = "Qwen/Qwen2.5-1.5B-Instruct" #беру модель полегче, тк мое устройство не супер мощное по памяти 

    try:
        tokenizer = AutoTokenizer.from_pretrained(
            model_name,
            trust_remote_code=True
        )
        # Настройка 4-битной квантизации (для сохранения памяти устройства и ускорения)
        bnb_config = BitsAndBytesConfig(
            load_in_4bit=True,                      
            bnb_4bit_quant_type="nf4", 
            bnb_4bit_compute_dtype=torch.float16, 
            bnb_4bit_use_double_quant=True          
        )
        
        model = AutoModelForCausalLM.from_pretrained(
            model_name,
            trust_remote_code=True,
            device_map="auto",
            dtype=torch.float16 if device == "cuda" else torch.float32,  # экономия памяти
            low_cpu_mem_usage=True
        )
        print("   Модель загружена")
    except Exception as e:
        print(f"   Ошибка загрузки модели: {e}")
        return []
    
    synthetic_pairs = [] #складываем все сгенерированное
    
    for idx, row in df.iterrows():
        book_id = row['book_id']
        annotation = row['annotation']
        title = row['title']
        
        print(f"    Книга {idx+1}/{len(df)}: {title[:30]}...")

        # Промпт для Qwen (формат как для чат-модели)
        messages = [
            {"role": "system", "content": "Ты помогаешь создать датасет для поисковой системы по книгам. Генерируй только запросы, без пояснений."},
            {"role": "user", "content": f"""Сгенерируй {queries_per_book} реалистичных поисковых запросов на русском языке, которые пользователь мог бы ввести, чтобы найти эту книгу.

Название книги: {title}
Описание книги: {annotation}

Требования:
1. Все запросы должны быть на русском языке
2. Используй разные формулировки: вопросы, утверждения, ключевые слова
3. Не используй название книги в запросах
4. Каждый запрос с новой строки, без нумерации

Сгенерируй запросы:"""}
        ]

        # Применяем шаблон чата Qwen
        text = tokenizer.apply_chat_template(
            messages,
            tokenize=False,
            add_generation_prompt=True
        )

        
        # Пробуем сгенерировать с повторными попытками
        for attempt in range(max_retries):
            try:
                # Токенизируем
                inputs = tokenizer([text], return_tensors="pt").to(model.device)
                
                # Генерируем
                with torch.no_grad():
                    outputs = model.generate(
                        **inputs,
                        max_new_tokens=300,
                        temperature=0.8,
                        do_sample=True,
                        top_p=0.9,
                        pad_token_id=tokenizer.eos_token_id
                    )
                    # Декодируем
                generated_text = tokenizer.decode(outputs[0], skip_special_tokens=True)
                
                # Извлекаем только сгенерированную часть (после промпта)
                # Ищем начало ответа
                if "Сгенерируй запросы:" in generated_text:
                    generated_text = generated_text.split("Сгенерируй запросы:")[-1]
                elif "assistant" in generated_text:
                    generated_text = generated_text.split("assistant")[-1]
                
                # Разбиваем на строки и чистим
                queries = generated_text.strip().split('\n')
                queries = [q.strip() for q in queries if q.strip()]
                
                # Удаляем возможную нумерацию
                cleaned_queries = []
                for q in queries:
                    q = re.sub(r'^\d+[\.\)]\s*', '', q)
                    q = re.sub(r'^[\-\*]\s*', '', q)
                    q = re.sub(r'^["\']|["\']$', '', q)
                    if q and len(q) > 3:  # фильтруем слишком короткие
                        cleaned_queries.append(q.strip())

                # Берем первые queries_per_book запросов
                for q in cleaned_queries[:queries_per_book]:
                    if q:
                        synthetic_pairs.append({
                            'query': q,
                            'book_id': book_id,
                            'source': 'synthetic_qwen',
                            'book_title': title
                        })
                
                print(f"Сгенерировано {len(cleaned_queries[:queries_per_book])} запросов")
                break  # успешно, выходим из retry


            except Exception as e:
                print(f"Попытка {attempt+1}/{max_retries} ошибка: {e}")
                if attempt < max_retries - 1:
                    time.sleep(2 ** attempt)
                else:
                    print(f"Не удалось сгенерировать запросы для '{title}'")

        # Небольшая задержка между запросами
        time.sleep(0.5)
        
        # Очищаем кэш GPU (если используем CUDA)
        if torch.cuda.is_available():
            torch.cuda.empty_cache()

    print(f"\n Сгенерировано синтетических запросов: {len(synthetic_pairs)}")
    return synthetic_pairs

In [ ]:
#запуск генерации запроса сразу с моей готовой таблицей (с помощью дип сик, первый опыт запуска генерации через код)

synthetic_pairs = synthetic_queries_qwen(
    df=books_df_id,
    queries_per_book=4
)
            
# Сохраняем результат
if synthetic_pairs:
    book_df_synth = pd.DataFrame(synthetic_pairs)
    book_df_synth.to_csv('/Users/uliaocheretina/Desktop/Комп лингв/ML Practice/FINAL_PROJECT_ML/books_synth.csv', index=False, encoding='utf-8')
    books_df_synth = pd.read_csv('books_synth.csv', encoding='utf-8')

    print(f"   - books_synth.csv ({len(synthetic_pairs)} запросов)")

    #примеры генерации
    print("\n примеры:")
    for i in range(min(4, len(synthetic_pairs))):
        pair = synthetic_pairs[i]
        print(f"\n   {i+1}. Запрос: '{pair['query']}'")
        print(f"      → Книга: {pair['book_title']}")
else:
    print("\n Не удалось сгенерировать запросы. Проверьте установку модели.")


#данная часть была сделана в коллабе, тк мое устройсвто недостаотчно мощное, чтобы делать это быстро 
#код тот же, только с сохранением промежуточного результата на гугл диск из-за большого объема данных
#upd: коллаб так же оборвал мне доступ к ускорителю, в итоге сгенерировав запросы на 3000 книг

In [ ]:
#имеем две таблицы, связанные айдишником книги 
books_df_id #табличка с айди и аннтоцией 
books_synth = pd.read_csv('queries_progress.csv', encoding='utf-8') #табличка с айди и запросом

# объединяем таблицы по названию книги, тк при генерации запросов, книгам присвоились новые айдишники
books_full = books_synth.merge(books_df_id[['title', 'annotation', 'link', 'book_id']], left_on='book_title', right_on='title', how='left')

# Проверяем, что аннотации подтянулись
print(f"Колонки: {books_full.columns.tolist()}")

# Смотрим пример
print(books_full[['book_title', 'query', 'annotation']].head(3))

In [10]:
#удаляем ненужные колонки
books_full=books_full.drop(columns=['book_id_x', 'book_title']) #оставляем только те, что были из таблицы с книгами 
books_full=books_full.rename(columns={'book_id_y': 'book_id'})

In [ ]:
#подчистка:
# Удаляем запросы, которые равны "assistant" (баг после генерации)
books_fin_0 = books_full[books_full['query'] != 'assistant']

books_fin_0

In [13]:
#сохраняем таблицу
books_fin_0.to_csv('/Users/uliaocheretina/Desktop/Комп лингв/ML Practice/FINAL_PROJECT_ML/books_join_id_query.csv', index=False, encoding='utf-8-sig')
books_fin = pd.read_csv('books_join_id_query.csv', encoding='utf-8')
#запрос составлен ни на каждую из 17.000 книг, а только на 3000 книг

In [ ]:
#финальная работа с датасетом это добавление рангов, на каждую книгу нужно лейблами добавить отзывы, которые к ней подходят и не подходят (positive/negative)
#upd: изначально было создан дизбаланс классов, но результаты обучения оказались не лучшими, и было принято решение сделать соотношение отзывов 1:1
def pos_neg (df, balance_ratio=1.0, random_seed=42):
    #группируем запрос по книгам
    queries_by_book = df.groupby('book_id')['query'].apply(list).to_dict()
    book_ids = list(queries_by_book.keys())

    #собираем информацию о книгах
    book_info = df.drop_duplicates('book_id').set_index('book_id')[['title', 'annotation', 'link']].to_dict('index')

    #для негативных примеров нам нужно еще раз собрать все запросы
    all_queries = []
    for bid, qs in queries_by_book.items():
        for q in qs:
            all_queries.append({'book_id': bid, 'query': q})


    #правильные запросы
    positive = []
    for book_id, queries in queries_by_book.items():
        info = book_info[book_id]
        for query in queries:
            positive.append({
                'book_id': book_id,
                'title': info['title'],
                'annotation': info['annotation'],
                'link': info['link'],
                'query': query,
                'label': 1
            })
    
    print(f"подходящих примеров: {len(positive)}")

    #неверные запросы
    negative = []
    
    for book_id, queries in queries_by_book.items():
        info = book_info[book_id]
        
        #нужное кол-во
        n_needed = int(len(queries) * balance_ratio)
        #используем запросы других книг
        other_queries = [q for q in all_queries if q['book_id'] != book_id]
        #проверяем достаточно ли запросов
        if len(other_queries) >= n_needed:
            selected = random.sample(other_queries, n_needed)
        else:
        #берем повторки если что
            selected = random.choices(other_queries, k=n_needed)
        
        for item in selected:
            negative.append({
                'book_id': book_id,
                'title': info['title'],
                'annotation': info['annotation'],
                'link': info['link'],
                'query': item['query'], 
                'label': 0
            })
    
    print(f"Негативных примеров: {len(negative)}")

    # объединяем и перемешиваем
    result = pd.DataFrame(positive + negative)
    result = result.sample(frac=1, random_state=random_seed).reset_index(drop=True)
    print(f"\n {len(result)} примеров")
    print(f"Соотношение: 1:{len(negative) / len(positive):.1f}")
    
    return result

In [15]:
books_neg_pos=pos_neg(books_fin, balance_ratio=1.0)

   подходящих примеров: 14289
   Негативных примеров: 14289

 28578 примеров
   Соотношение: 1:1.0

In [ ]:
# проверка
print(books_neg_pos.head())

In [18]:
books_neg_pos.to_csv('/Users/uliaocheretina/Desktop/Комп лингв/ML Practice/FINAL_PROJECT_ML/books_neg_pos.csv', index=False, encoding='utf-8-sig')

books_pn = pd.read_csv('books_neg_pos.csv', encoding='utf-8')

In [ ]:
#приступаем к препроцессингу и токенизации данных

def clean_text(text, language='russian'):
    text = text. lower() #приводим к нижнему регистру
    text = re.sub(r'http\S+|www\S+', ' ', text) #удаляем все похожее на ссылку
    text = re.sub(r'[^a-zа-яё\s]', '', text)  #удаляем все символы кроме букв
    text = re. sub(r'\s+', ' ', text) #убираем лишние пробелы
    tokens=text.split() #токенизируем
    stop_words = set(stopwords.words('russian')) #убираем стоп слова
    return ' '.join(tokens)


#title не трогаем, название нам нужно сырым, чтобы пользователю подгружался оригинал
#очиситим только аннотацию и запросы
books_pn['clean annotation']=books_pn['annotation'].apply(clean_text) #добавляем колонку с чистой аннотацией
books_pn['clean query']=books_pn['query'].apply(clean_text) #добавляем колонку с чистым запросом

books_pn

In [20]:
books_pn.to_csv('/Users/uliaocheretina/Desktop/Комп лингв/ML Practice/FINAL_PROJECT_ML/books_pn.csv', index=False, encoding='utf-8-sig')

In [21]:
#посмотрим итоговую табличку

books_pn.info() #два типа данных числа и текст, построчно все совпадает
print(f'пустые строки:{books_pn.isnull().values.any()}') #пустых строк нет 
print(f'повторяющиеся тексты:{books_pn.duplicated().any()}') #знаю момент с повторками: некоторые из книг подгрузились два раза, тк на сайте они дублируются, только одна ссылкой на бумажный носитель, а другая на литрес
#но решила все равно оставить, вдруг пригодится в будущем

<class 'pandas.DataFrame'>
RangeIndex: 28578 entries, 0 to 28577
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   book_id           28578 non-null  str
 1   title             28578 non-null  str
 2   annotation        28578 non-null  str
 3   link              28578 non-null  str
 4   query             28578 non-null  str
 5   label             28578 non-null  int64
 6   clean annotation  28578 non-null  str
 7   clean query       28578 non-null  str
dtypes: int64(1), str(7)
memory usage: 81.8 MB
пустые строки:False
повторяющиеся тексты:True

In [22]:
#смотрим дисбаланс классов
books_pn.describe()

#исправили дизбаланс

              label
count  28578.000000
mean       0.500000
std        0.500009
min        0.000000
25%        0.000000
50%        0.500000
75%        1.000000
max        1.000000

In [ ]:
#в процессе был найден еще мусор, убираем
df_clean = books_pn[~books_pn['clean annotation'].str.contains('открывается в программе adobe reader', case=False, na=False)]

df_clean = books_pn[~books_pn['link'].str.contains('litres.ru', case=False, na=False)]

In [ ]:
#было принято попробовать использовать модель логистической регрессии с дальнейшим ранжированием :
#соотвтетсвенно в X мы отправим совмещенные запрос пользователя и аннотацию
#а в у пойдет сам лейбл соответствия: то есть праивльный ответ подходит ли запрос пользователя к аннотации -> если аннотация соотвносится с запросом то к ней по айдишнику подтянется название
#то есть мы обучим модель понимать, подходит ли запрос к аннотации или нет, и на этйо основе уже будет подтягиваться книга 

df_clean['text'] = df_clean['clean query'] + ' [SEP] ' + df_clean['clean annotation'] #объединим колонки

In [29]:
df_clean.to_csv('/Users/uliaocheretina/Desktop/Комп лингв/ML Practice/FINAL_PROJECT_ML/books_pn_text.csv', index=False, encoding='utf-8-sig')

In [30]:
#переходим к распределению материалов
#передаем сразу очищенный текст

train_df, test_df = train_test_split( #определим, что у нас есть материал для для трейна и для теста
    df_clean,
    test_size=0.2,
    random_state=42,
    stratify=df_clean['label']   
)

In [ ]:
#определяем Х и у
X=df_clean['text'].tolist()
y=df_clean['label'].values #таргет уже разбит на бинарник (1, 0), не нуждается в доп кодировании

In [31]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42) #делим на выборки

In [32]:
#извлечение вектора из текстовых значений
vectorizer=TfidfVectorizer(max_features=5000) #определяем модель векторизации

X_train_vec=vectorizer.fit_transform(X_train) #обучать будем на трейн (тк работаем с обучением с учителем)
X_test_vec=vectorizer.transform(X_test) #тестовую только векторизуем 

print(X_train_vec.shape) #проверяем размерность
print(X_test_vec.shape)

(22862, 5000)
(5716, 5000)

In [33]:
print(type(X_train_vec))

<class 'scipy.sparse._csr.csr_matrix'>

In [34]:
#масштабируем признаки для более точных результатов 
scaler = StandardScaler(with_mean=False)  
X_train_sc = scaler.fit_transform(X_train_vec)
X_test_sc = scaler.transform(X_test_vec)

In [35]:
#обучение модели: берем метод классификации 
#нас интересуем LR

#Логистическая регрессия (баланс классов не нужен, они уже сбалансированы)
model1=LogisticRegression(random_state=42, max_iter=1000)

model1.fit(X_train_sc, y_train)

y_predict1=model1.predict(X_test_sc)

In [36]:
#посмотрим результаты 

print('Логистическая регрессия')
print(classification_report(y_test, y_predict1))

Логистическая регрессия
              precision    recall  f1-score   support

           0       0.42      0.42      0.42      2864
           1       0.41      0.41      0.41      2852

    accuracy                           0.41      5716
   macro avg       0.41      0.41      0.41      5716
weighted avg       0.41      0.41      0.41      5716

In [41]:
#ПРИМЕЧАНИЕ: при обучении модели, признаки оказались ужасными, пробуем улучшить результат посредством обучения на эмбеддингах а не векторах
#пробуем модель фрида мини, одна из лучших и небольших в области работы с русским языком

model_name = "sergeyzh/rubert-mini-frida"
embedder = SentenceTransformer(model_name)

if torch.cuda.is_available():
    embedder = embedder.to('cuda')
    device = "GPU"
else:
    device = "CPU"

print(f"   Модель загружена: {model_name}")

Loading weights: 100%|██████████| 119/119 [00:00<00:00, 6408.20it/s]

   Модель загружена: sergeyzh/rubert-mini-frida

In [ ]:
#создание эмбеддингов
#ПРИМЕЧАНИЕ: не хватило мощности компьютера, перешла в коллаб для выполнения этого шага в облаке
X_train_emb = embedder.encode(
    X_train,
    batch_size=64,
    show_progress_bar=True,
    convert_to_numpy=True,
    normalize_embeddings=True,
    precision='float32' 
)

X_test_emb = embedder.encode(
    X_test,
    batch_size=64,
    show_progress_bar=True,
    convert_to_numpy=True,
    normalize_embeddings=True,
    precision='float32' 
)

In [ ]:
scaler = StandardScaler()
X_train_sc_em = scaler.fit_transform(X_train_emb)
X_test_sc_em = scaler.transform(X_test_emb)

In [ ]:
model3=LogisticRegression(random_state=42, max_iter=1000)

model3.fit(X_train_sc_em, y_train)

y_predict3=model3.predict(X_test_sc_em)

In [ ]:
print('Логистическая регрессия с балансом классов на эмбеддингах')
print(classification_report(y_test, y_predict3))

In [ ]:
#далее вторая часть в коллабе "Frida"